# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T10:12:19.432Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.request import Request

class TestRequest(unittest.TestCase):
    """Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Request:
        """Test Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Request`
        """
        model = Request()
        if include_optional:
            return Request(
                id = 'ueJDL982Hs',
                created_at = None,
                updated_at = None,
                auth_amount = None,
                server_emp_id = None,
                module_invoked = None,
                cashier_emp_id = None,
                routing_id = None,
                auth_account_num = None,
                more_records_count = None,
                payment_method_id = None,
                tag_data = None,
                total_auth_amount = None,
                refund_flag = None,
                close_time = None,
                client_id = None,
                change_amount = None,
                employee_id = 'ueJDL982Hs',
                training_mode_flag = None,
                source_property_id = None,
                associated_check_number = None,
                post_to_property_id = None,
                unique_posting_id = None,
                expire_date = None,
                by_name_flag = None,
                payment_slip_id = None,
                financial_bin_detail = None,
                cvv2 = None,
                employee_grat_tip = None,
                card_swipe_track1 = None,
                card_swipe_track2 = None,
                check_number = None,
                more_records_key = None,
                tip_amount = None,
                input_data = None,
                profit_center_id = None,
                invoice_number = None,
                receipt_text_image = None,
                brokerage_amount = None,
                amount = None,
                cover_count = None,
                more_records_flag = None,
                account_num = None,
                max_record_count = None,
                incremental_auth_amount = None,
                extra_data = None,
                check_type_id = None,
                posting_id = None,
                destination_property_id = None,
                account_detail = None,
                payment_amount = None,
                register_id = None,
                tndr_account_object = None,
                meal_period_id = None
            )
        else:
            return Request(
                id = 'ueJDL982Hs',
                created_at = None,
                updated_at = None,
                auth_amount = None,
                server_emp_id = None,
                module_invoked = None,
                cashier_emp_id = None,
                routing_id = None,
                auth_account_num = None,
                more_records_count = None,
                payment_method_id = None,
                tag_data = None,
                total_auth_amount = None,
                refund_flag = None,
                close_time = None,
                client_id = None,
                change_amount = None,
                employee_id = 'ueJDL982Hs',
                training_mode_flag = None,
                source_property_id = None,
                associated_check_number = None,
                post_to_property_id = None,
                unique_posting_id = None,
                expire_date = None,
                by_name_flag = None,
                payment_slip_id = None,
                financial_bin_detail = None,
                cvv2 = None,
                employee_grat_tip = None,
                card_swipe_track1 = None,
                card_swipe_track2 = None,
                check_number = None,
                more_records_key = None,
                tip_amount = None,
                input_data = None,
                profit_center_id = None,
                invoice_number = None,
                receipt_text_image = None,
                brokerage_amount = None,
                amount = None,
                cover_count = None,
                more_records_flag = None,
                account_num = None,
                max_record_count = None,
                incremental_auth_amount = None,
                extra_data = None,
                check_type_id = None,
                posting_id = None,
                destination_property_id = None,
                account_detail = None,
                payment_amount = None,
                register_id = None,
                tndr_account_object = None,
                meal_period_id = None,
        )
        """

    def testRequest(self):
        """Test Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
