# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T14:20:49.899Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_virtual_business_card_update_params import WTVirtualBusinessCardUpdateParams

class TestWTVirtualBusinessCardUpdateParams(unittest.TestCase):
    """WTVirtualBusinessCardUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTVirtualBusinessCardUpdateParams:
        """Test WTVirtualBusinessCardUpdateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTVirtualBusinessCardUpdateParams`
        """
        model = WTVirtualBusinessCardUpdateParams()
        if include_optional:
            return WTVirtualBusinessCardUpdateParams(
                first_name = 'John',
                last_name = 'Smith',
                email_address = None,
                designation = Founder & CEO,
                phone_number = +1 (800) 123-4567,
                introduction = John was born into the F&B world. His grandparents owned a restaurant in the 1960s in Lorraine, France. His brother is a chef and his uncle is a famous chef in the U.S. ...,
                instagram = your_IG_handle,
                facebook = page ID or handle,
                you_tube = channel ID or handle,
                twitter = your_handle,
                linked_in = company ID or handle,
                whats_app = WhatsApp number,
                avatar_url = https://media.wall.et/m/abc/avatar.png
            )
        else:
            return WTVirtualBusinessCardUpdateParams(
                first_name = 'John',
                last_name = 'Smith',
                email_address = None,
                designation = Founder & CEO,
                phone_number = +1 (800) 123-4567,
        )
        """

    def testWTVirtualBusinessCardUpdateParams(self):
        """Test WTVirtualBusinessCardUpdateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
