# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T11:07:48.885Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_room_rate_update_params import WTRoomRateUpdateParams

class TestWTRoomRateUpdateParams(unittest.TestCase):
    """WTRoomRateUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTRoomRateUpdateParams:
        """Test WTRoomRateUpdateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTRoomRateUpdateParams`
        """
        model = WTRoomRateUpdateParams()
        if include_optional:
            return WTRoomRateUpdateParams(
                title = This is the title of the room & rate,
                description = This is the description of the room & rate,
                displayed_price = $200-$350,
                order_number = 1,
                media_url = 'https://wall.et/media/H847Sjudbw.png',
                additional_info_url = https://hotels.com/your-property/king-bedroom
            )
        else:
            return WTRoomRateUpdateParams(
                title = This is the title of the room & rate,
                description = This is the description of the room & rate,
                order_number = 1,
        )
        """

    def testWTRoomRateUpdateParams(self):
        """Test WTRoomRateUpdateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
