# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T11:07:48.885Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_email_subscriber_create_params_wallet_ui import WTEmailSubscriberCreateParamsWalletUI

class TestWTEmailSubscriberCreateParamsWalletUI(unittest.TestCase):
    """WTEmailSubscriberCreateParamsWalletUI unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTEmailSubscriberCreateParamsWalletUI:
        """Test WTEmailSubscriberCreateParamsWalletUI
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTEmailSubscriberCreateParamsWalletUI`
        """
        model = WTEmailSubscriberCreateParamsWalletUI()
        if include_optional:
            return WTEmailSubscriberCreateParamsWalletUI(
                first_name = John,
                last_name = Smith,
                email_address = None,
                merchant_id = 'ueJDL982Hs'
            )
        else:
            return WTEmailSubscriberCreateParamsWalletUI(
                first_name = John,
                last_name = Smith,
                email_address = None,
                merchant_id = 'ueJDL982Hs',
        )
        """

    def testWTEmailSubscriberCreateParamsWalletUI(self):
        """Test WTEmailSubscriberCreateParamsWalletUI"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
