# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T11:20:36.694Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_employee_send_help_desk_response import WTEmployeeSendHelpDeskResponse

class TestWTEmployeeSendHelpDeskResponse(unittest.TestCase):
    """WTEmployeeSendHelpDeskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTEmployeeSendHelpDeskResponse:
        """Test WTEmployeeSendHelpDeskResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTEmployeeSendHelpDeskResponse`
        """
        model = WTEmployeeSendHelpDeskResponse()
        if include_optional:
            return WTEmployeeSendHelpDeskResponse(
                help_desk_request_id = 'ueJDL982Hs',
                message = Good morning! How can I help you today?,
                media_urls = [https://example.com/media.jpeg]
            )
        else:
            return WTEmployeeSendHelpDeskResponse(
                help_desk_request_id = 'ueJDL982Hs',
                message = Good morning! How can I help you today?,
        )
        """

    def testWTEmployeeSendHelpDeskResponse(self):
        """Test WTEmployeeSendHelpDeskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
