# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:48:48.361Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.business_registration_identifier import BusinessRegistrationIdentifier

class TestBusinessRegistrationIdentifier(unittest.TestCase):
    """BusinessRegistrationIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessRegistrationIdentifier(self):
        """Test BusinessRegistrationIdentifier"""
        # inst = BusinessRegistrationIdentifier()

if __name__ == '__main__':
    unittest.main()
