"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import unittest

import wallet
from wallet.api.dining_api import DiningApi  # noqa: E501


class TestDiningApi(unittest.TestCase):
    """DiningApi unit test stubs"""

    def setUp(self):
        self.api = DiningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_dining(self):
        """Test case for archive_dining

        Archive dining  # noqa: E501
        """
        pass

    def test_create_dining(self):
        """Test case for create_dining

        Create dining  # noqa: E501
        """
        pass

    def test_fetch_all_dining(self):
        """Test case for fetch_all_dining

        Fetch all dining  # noqa: E501
        """
        pass

    def test_restore_dining(self):
        """Test case for restore_dining

        Restore dining  # noqa: E501
        """
        pass

    def test_update_dining(self):
        """Test case for update_dining

        Update dining  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
