# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.0**, built 2026-07-08T17:05:52.109Z

    The version of the OpenAPI document: 2.4.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.ms_analytics_membership_tier_amount_redeemed_partitioned_by_date import MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate

class TestMSAnalyticsMembershipTierAmountRedeemedPartitionedByDate(unittest.TestCase):
    """MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate:
        """Test MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate`
        """
        model = MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate()
        if include_optional:
            return MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate(
                var_date = 2016-06-22,
                amount = 25816
            )
        else:
            return MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate(
                var_date = 2016-06-22,
                amount = 25816,
        )
        """

    def testMSAnalyticsMembershipTierAmountRedeemedPartitionedByDate(self):
        """Test MSAnalyticsMembershipTierAmountRedeemedPartitionedByDate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
