# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:37:07.333Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.payment_designs_api import PaymentDesignsApi


class TestPaymentDesignsApi(unittest.TestCase):
    """PaymentDesignsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentDesignsApi()

    def tearDown(self) -> None:
        pass

    def test_archive_payment_design(self) -> None:
        """Test case for archive_payment_design

        Archive payment design
        """
        pass

    def test_create_payment_design(self) -> None:
        """Test case for create_payment_design

        Create payment design
        """
        pass

    def test_fetch_all_payment_designs(self) -> None:
        """Test case for fetch_all_payment_designs

        Get all payment designs
        """
        pass

    def test_fetch_payment_design_by_id(self) -> None:
        """Test case for fetch_payment_design_by_id

        Get payment design
        """
        pass

    def test_restore_payment_design(self) -> None:
        """Test case for restore_payment_design

        Restore payment design
        """
        pass

    def test_update_payment_design(self) -> None:
        """Test case for update_payment_design

        Update payment design
        """
        pass


if __name__ == '__main__':
    unittest.main()
