"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.message_status_any_of import MessageStatusAnyOf
from wallet.model.message_status_any_of1 import MessageStatusAnyOf1
from wallet.model.message_status_any_of2 import MessageStatusAnyOf2
from wallet.model.message_status_any_of3 import MessageStatusAnyOf3
from wallet.model.message_status_any_of4 import MessageStatusAnyOf4
from wallet.model.message_status_any_of5 import MessageStatusAnyOf5
from wallet.model.message_status_any_of6 import MessageStatusAnyOf6
from wallet.model.message_status_any_of7 import MessageStatusAnyOf7
from wallet.model.ss_outbound_statuses_any_of import SSOutboundStatusesAnyOf
from wallet.model.ss_outbound_statuses_any_of1 import SSOutboundStatusesAnyOf1
from wallet.model.ss_outbound_statuses_any_of2 import SSOutboundStatusesAnyOf2
from wallet.model.ss_outbound_statuses_any_of3 import SSOutboundStatusesAnyOf3
from wallet.model.ss_outbound_statuses_any_of4 import SSOutboundStatusesAnyOf4
globals()['MessageStatusAnyOf'] = MessageStatusAnyOf
globals()['MessageStatusAnyOf1'] = MessageStatusAnyOf1
globals()['MessageStatusAnyOf2'] = MessageStatusAnyOf2
globals()['MessageStatusAnyOf3'] = MessageStatusAnyOf3
globals()['MessageStatusAnyOf4'] = MessageStatusAnyOf4
globals()['MessageStatusAnyOf5'] = MessageStatusAnyOf5
globals()['MessageStatusAnyOf6'] = MessageStatusAnyOf6
globals()['MessageStatusAnyOf7'] = MessageStatusAnyOf7
globals()['SSOutboundStatusesAnyOf'] = SSOutboundStatusesAnyOf
globals()['SSOutboundStatusesAnyOf1'] = SSOutboundStatusesAnyOf1
globals()['SSOutboundStatusesAnyOf2'] = SSOutboundStatusesAnyOf2
globals()['SSOutboundStatusesAnyOf3'] = SSOutboundStatusesAnyOf3
globals()['SSOutboundStatusesAnyOf4'] = SSOutboundStatusesAnyOf4
from wallet.model.message_status import MessageStatus


class TestMessageStatus(unittest.TestCase):
    """MessageStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageStatus(self):
        """Test MessageStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
