# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T17:01:44.199Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.pick_wt_employee_create_exclude_keyof_wt_employee_create_email_schedule_start_meridiem import PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem

class TestPickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem(unittest.TestCase):
    """PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem:
        """Test PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem`
        """
        model = PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem()
        if include_optional:
            return PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem(
            )
        else:
            return PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem(
        )
        """

    def testPickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem(self):
        """Test PickWTEmployeeCreateExcludeKeyofWTEmployeeCreateEmailScheduleStartMeridiem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
