# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T22:41:01.331Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_employee_schedule_simple_sms import WTEmployeeScheduleSimpleSMS

class TestWTEmployeeScheduleSimpleSMS(unittest.TestCase):
    """WTEmployeeScheduleSimpleSMS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTEmployeeScheduleSimpleSMS:
        """Test WTEmployeeScheduleSimpleSMS
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTEmployeeScheduleSimpleSMS`
        """
        model = WTEmployeeScheduleSimpleSMS()
        if include_optional:
            return WTEmployeeScheduleSimpleSMS(
                phone_number_id = 'ueJDL982Hs',
                message_template = We're running a year end promo of flat 50% off!,
                media_urls = [https://example.com/media.jpeg],
                broadcast_scheduled_at = 2022-08-17T18:42:50.713Z,
                list_type = opt-in-keyword-list,
                list_id = 'ueJDL982Hs'
            )
        else:
            return WTEmployeeScheduleSimpleSMS(
                phone_number_id = 'ueJDL982Hs',
                message_template = We're running a year end promo of flat 50% off!,
                broadcast_scheduled_at = 2022-08-17T18:42:50.713Z,
                list_type = opt-in-keyword-list,
                list_id = 'ueJDL982Hs',
        )
        """

    def testWTEmployeeScheduleSimpleSMS(self):
        """Test WTEmployeeScheduleSimpleSMS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
