# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.0**, built 2026-07-08T17:05:52.109Z

    The version of the OpenAPI document: 2.4.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.business_classification import BusinessClassification

class TestBusinessClassification(unittest.TestCase):
    """BusinessClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessClassification(self):
        """Test BusinessClassification"""
        # inst = BusinessClassification()

if __name__ == '__main__':
    unittest.main()
