# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:48:48.361Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.promo_code import PromoCode

class TestPromoCode(unittest.TestCase):
    """PromoCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromoCode:
        """Test PromoCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromoCode`
        """
        model = PromoCode()
        if include_optional:
            return PromoCode(
                title = This is the title of the promo code,
                description = This is the description of the promo code,
                promo_code = XMAS20,
                display_value = 20% Off!,
                order_number = 1,
                media_url = https://wall.et/media/H847Sjudbw.png,
                start_date = 2016-06-22 19:10:25-07,
                expiration_date = 2016-06-22 19:10:25-07,
                id = None,
                created_at = None,
                updated_at = None,
                is_active = None,
                merchant_id = 'ueJDL982Hs'
            )
        else:
            return PromoCode(
                title = This is the title of the promo code,
                description = This is the description of the promo code,
                promo_code = XMAS20,
                display_value = 20% Off!,
                order_number = 1,
                start_date = 2016-06-22 19:10:25-07,
                expiration_date = 2016-06-22 19:10:25-07,
                id = None,
                created_at = None,
                updated_at = None,
                is_active = None,
                merchant_id = 'ueJDL982Hs',
        )
        """

    def testPromoCode(self):
        """Test PromoCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
