# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.7.3**, built 2026-07-14T04:37:03.852Z

    The version of the OpenAPI document: 2.7.3
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.ticket_sort_keys import TicketSortKeys

class TestTicketSortKeys(unittest.TestCase):
    """TicketSortKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketSortKeys(self):
        """Test TicketSortKeys"""
        # inst = TicketSortKeys()

if __name__ == '__main__':
    unittest.main()
