# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.3**, built 2026-07-09T22:41:33.079Z

    The version of the OpenAPI document: 2.4.3
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_membership_tier_with_member_count import WTMembershipTierWithMemberCount

class TestWTMembershipTierWithMemberCount(unittest.TestCase):
    """WTMembershipTierWithMemberCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTMembershipTierWithMemberCount:
        """Test WTMembershipTierWithMemberCount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTMembershipTierWithMemberCount`
        """
        model = WTMembershipTierWithMemberCount()
        if include_optional:
            return WTMembershipTierWithMemberCount(
                tier_number = 101,
                tier_name = Gold,
                tier_discount = 25,
                tier_design_id = 'ueJDL982Hs',
                points_design_id = 'ueJDL982Hs',
                id = jdu37eua98,
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                member_count = 20
            )
        else:
            return WTMembershipTierWithMemberCount(
                tier_number = 101,
                tier_name = Gold,
                tier_discount = 25,
                tier_design_id = 'ueJDL982Hs',
                points_design_id = 'ueJDL982Hs',
                id = jdu37eua98,
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                member_count = 20,
        )
        """

    def testWTMembershipTierWithMemberCount(self):
        """Test WTMembershipTierWithMemberCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
