# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T09:49:03.606Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.click_funnel_contact_profile import ClickFunnelContactProfile

class TestClickFunnelContactProfile(unittest.TestCase):
    """ClickFunnelContactProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClickFunnelContactProfile:
        """Test ClickFunnelContactProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClickFunnelContactProfile`
        """
        model = ClickFunnelContactProfile()
        if include_optional:
            return ClickFunnelContactProfile(
                id = 1.337,
                first_name = '',
                last_name = '',
                address = '',
                city = '',
                country = None,
                state = None,
                zip = '',
                email = '',
                phone = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                unsubscribed_at = None,
                cf_uvid = '',
                shipping_address = '',
                shipping_country = None,
                shipping_city = None,
                shipping_state = None,
                shipping_zip = None,
                vat_number = None,
                middle_name = None,
                websites = None,
                location_general = None,
                normalized_location = None,
                deduced_location = None,
                age = None,
                gender = None,
                age_range_lower = None,
                age_range_upper = None,
                action_score = None,
                known_ltv = '',
                tags = None,
                time_zone = None,
                lists_names = '',
                globally_unsubscribed = True
            )
        else:
            return ClickFunnelContactProfile(
                id = 1.337,
                first_name = '',
                last_name = '',
                address = '',
                city = '',
                zip = '',
                email = '',
                phone = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cf_uvid = '',
                known_ltv = '',
                tags = None,
                globally_unsubscribed = True,
        )
        """

    def testClickFunnelContactProfile(self):
        """Test ClickFunnelContactProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
