# coding: utf-8

"""
    wallet-api

    API

    The version of the OpenAPI document: 2.1.600
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.club_members_points_api import ClubMembersPointsApi


class TestClubMembersPointsApi(unittest.TestCase):
    """ClubMembersPointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClubMembersPointsApi()

    def tearDown(self) -> None:
        pass

    def test_archive_member(self) -> None:
        """Test case for archive_member

        Archive member
        """
        pass

    def test_create_member(self) -> None:
        """Test case for create_member

        Create member
        """
        pass

    def test_fetch_member_by_id(self) -> None:
        """Test case for fetch_member_by_id

        Fetch member
        """
        pass

    def test_fetch_member_history_log(self) -> None:
        """Test case for fetch_member_history_log

        Fetch history
        """
        pass

    def test_fetch_member_redemption_log(self) -> None:
        """Test case for fetch_member_redemption_log

        Fetch redemption log
        """
        pass

    def test_fetch_members_by_page(self) -> None:
        """Test case for fetch_members_by_page

        Fetch members by page
        """
        pass

    def test_fetch_members_count(self) -> None:
        """Test case for fetch_members_count

        Count active members
        """
        pass

    def test_restore_member(self) -> None:
        """Test case for restore_member

        Restore member
        """
        pass

    def test_search_members(self) -> None:
        """Test case for search_members

        Search for members
        """
        pass

    def test_update_member(self) -> None:
        """Test case for update_member

        Update member
        """
        pass


if __name__ == '__main__':
    unittest.main()
