# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T12:42:39.186Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.imported_list_recipient import ImportedListRecipient

class TestImportedListRecipient(unittest.TestCase):
    """ImportedListRecipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportedListRecipient:
        """Test ImportedListRecipient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportedListRecipient`
        """
        model = ImportedListRecipient()
        if include_optional:
            return ImportedListRecipient(
                imported_list_id = '0123456789',
                mobile_phone_number = +18047552674,
                id = jdu37eua98,
                merchant_id = '0123456789',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                opted_status = None
            )
        else:
            return ImportedListRecipient(
                imported_list_id = '0123456789',
                mobile_phone_number = +18047552674,
                id = jdu37eua98,
                merchant_id = '0123456789',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
        )
        """

    def testImportedListRecipient(self):
        """Test ImportedListRecipient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
