# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.2**, built 2026-07-09T11:23:05.427Z

    The version of the OpenAPI document: 2.4.2
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_ticket import WTTicket

class TestWTTicket(unittest.TestCase):
    """WTTicket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTTicket:
        """Test WTTicket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTTicket`
        """
        model = WTTicket()
        if include_optional:
            return WTTicket(
                recipient_phone_number = '',
                recipient_email_address = '',
                recipient_member_id = '',
                is_comp = True,
                quantity = 1,
                performance_id = '',
                id = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_active = True,
                merchant_id = 'ueJDL982Hs',
                is_claimed = True,
                date_time_claimed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                claimed_by_phone_number = '',
                redeemed_source = '',
                redeemed_transaction_id = '',
                transaction_type = '',
                register_id = '',
                is_redeemed = True,
                date_time_redeemed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WTTicket(
                performance_id = '',
                id = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_active = True,
                merchant_id = 'ueJDL982Hs',
        )
        """

    def testWTTicket(self):
        """Test WTTicket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
