# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T15:40:46.402Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.a2_p_application_submission import A2PApplicationSubmission

class TestA2PApplicationSubmission(unittest.TestCase):
    """A2PApplicationSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> A2PApplicationSubmission:
        """Test A2PApplicationSubmission
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `A2PApplicationSubmission`
        """
        model = A2PApplicationSubmission()
        if include_optional:
            return A2PApplicationSubmission(
                is_twilio_terms_read = None,
                is_privacy_policy_on_website = None,
                is_tos_on_website = None,
                is_stop_understood = None,
                is_manual_read = None,
                is_ctia_short_code_read = None,
                is_standards_understood = None,
                is_short_code_understood = None,
                is_opt_in_out_understood = None,
                is_short_code_transfer_understood = None,
                is_pricing_understood = None,
                is_short_code_timeline_understood = None,
                business_name = Acme Corp,
                business_type = Corporation,
                business_classification = private,
                business_industry = private,
                tax_id_type = EIN,
                tax_id = 23-235235,
                website_url = https://google.com,
                social_media_url = https://instagram.com/your_business,
                regions_of_operation = AFRICA,
                stock_exchange = 'NONE',
                stock_ticker = None,
                messaging_volume_high = None,
                address1 = 21 Jump Street,
                address2 = https://google.com,
                city = Los Angeles,
                state = California,
                postal_code = 90210,
                country = US,
                first_name = John,
                last_name = Doe,
                email = None,
                job_title = VP of Marketing,
                job_position = Director,
                phone_number = +1 800 123 4567
            )
        else:
            return A2PApplicationSubmission(
                is_twilio_terms_read = None,
                is_privacy_policy_on_website = None,
                is_tos_on_website = None,
                is_stop_understood = None,
                is_manual_read = None,
                is_ctia_short_code_read = None,
                is_standards_understood = None,
                is_short_code_understood = None,
                is_opt_in_out_understood = None,
                is_short_code_transfer_understood = None,
                is_pricing_understood = None,
                is_short_code_timeline_understood = None,
                business_name = Acme Corp,
                business_type = Corporation,
                business_classification = private,
                business_industry = private,
                tax_id_type = EIN,
                tax_id = 23-235235,
                website_url = https://google.com,
                social_media_url = https://instagram.com/your_business,
                regions_of_operation = AFRICA,
                messaging_volume_high = None,
                address1 = 21 Jump Street,
                city = Los Angeles,
                state = California,
                postal_code = 90210,
                country = US,
                first_name = John,
                last_name = Doe,
                email = None,
                job_title = VP of Marketing,
                job_position = Director,
                phone_number = +1 800 123 4567,
        )
        """

    def testA2PApplicationSubmission(self):
        """Test A2PApplicationSubmission"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
