# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-11T12:12:04.130Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_image_grid_update_params import WTImageGridUpdateParams

class TestWTImageGridUpdateParams(unittest.TestCase):
    """WTImageGridUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTImageGridUpdateParams:
        """Test WTImageGridUpdateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTImageGridUpdateParams`
        """
        model = WTImageGridUpdateParams()
        if include_optional:
            return WTImageGridUpdateParams(
                title = This is the title of the image,
                url = 'https://example.com',
                media_url = https://example.com/image.gif,
                sequence_number = 1,
                is_pinned = True
            )
        else:
            return WTImageGridUpdateParams(
                title = This is the title of the image,
                url = 'https://example.com',
                media_url = https://example.com/image.gif,
                sequence_number = 1,
        )
        """

    def testWTImageGridUpdateParams(self):
        """Test WTImageGridUpdateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
