# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-13T17:18:17.401Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.wallet_transaction_ledger_api import WalletTransactionLedgerApi


class TestWalletTransactionLedgerApi(unittest.TestCase):
    """WalletTransactionLedgerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletTransactionLedgerApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_all_ledger_transactions(self) -> None:
        """Test case for fetch_all_ledger_transactions

        Get ledger entries
        """
        pass


if __name__ == '__main__':
    unittest.main()
