# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:48:48.361Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.quick_links_api import QuickLinksApi


class TestQuickLinksApi(unittest.TestCase):
    """QuickLinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuickLinksApi()

    def tearDown(self) -> None:
        pass

    def test_archive_link_book(self) -> None:
        """Test case for archive_link_book

        Archive Quick Link
        """
        pass

    def test_create_link_book(self) -> None:
        """Test case for create_link_book

        Create Quick Link
        """
        pass

    def test_fetch_all_link_book(self) -> None:
        """Test case for fetch_all_link_book

        Get all Quick Links
        """
        pass

    def test_fetch_link_book_by_id(self) -> None:
        """Test case for fetch_link_book_by_id

        Get Quick Link
        """
        pass

    def test_restore_link_book(self) -> None:
        """Test case for restore_link_book

        Restore Quick Link
        """
        pass

    def test_update_link_book(self) -> None:
        """Test case for update_link_book

        Update Quick Link
        """
        pass


if __name__ == '__main__':
    unittest.main()
