# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.7.1**, built 2026-07-14T02:00:08.523Z

    The version of the OpenAPI document: 2.7.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.quick_links_section_api import QuickLinksSectionApi


class TestQuickLinksSectionApi(unittest.TestCase):
    """QuickLinksSectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuickLinksSectionApi()

    def tearDown(self) -> None:
        pass

    def test_archive_link_book_section(self) -> None:
        """Test case for archive_link_book_section

        Archive quick link section
        """
        pass

    def test_create_link_book_section(self) -> None:
        """Test case for create_link_book_section

        Create quick link section
        """
        pass

    def test_fetch_all_link_book_sections(self) -> None:
        """Test case for fetch_all_link_book_sections

        Get all quick link sections
        """
        pass

    def test_restore_link_book_section(self) -> None:
        """Test case for restore_link_book_section

        Restore quick link section
        """
        pass

    def test_update_link_book_section(self) -> None:
        """Test case for update_link_book_section

        Update quick link section
        """
        pass


if __name__ == '__main__':
    unittest.main()
