"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.business_classification import BusinessClassification
from wallet.model.business_industry import BusinessIndustry
from wallet.model.business_regions_of_operation import BusinessRegionsOfOperation
from wallet.model.business_registration_identifier import BusinessRegistrationIdentifier
from wallet.model.business_stock_exchanges import BusinessStockExchanges
from wallet.model.business_type import BusinessType
from wallet.model.job_position import JobPosition
globals()['BusinessClassification'] = BusinessClassification
globals()['BusinessIndustry'] = BusinessIndustry
globals()['BusinessRegionsOfOperation'] = BusinessRegionsOfOperation
globals()['BusinessRegistrationIdentifier'] = BusinessRegistrationIdentifier
globals()['BusinessStockExchanges'] = BusinessStockExchanges
globals()['BusinessType'] = BusinessType
globals()['JobPosition'] = JobPosition
from wallet.model.a2_p_application_submission import A2PApplicationSubmission


class TestA2PApplicationSubmission(unittest.TestCase):
    """A2PApplicationSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testA2PApplicationSubmission(self):
        """Test A2PApplicationSubmission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = A2PApplicationSubmission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
