# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T01:54:12.502Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.lounge_api import LoungeApi


class TestLoungeApi(unittest.TestCase):
    """LoungeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoungeApi()

    def tearDown(self) -> None:
        pass

    def test_archive_lounge(self) -> None:
        """Test case for archive_lounge

        Archive Lounge
        """
        pass

    def test_create_lounge(self) -> None:
        """Test case for create_lounge

        Create Lounge
        """
        pass

    def test_fetch_all_lounge(self) -> None:
        """Test case for fetch_all_lounge

        Get all Lounges
        """
        pass

    def test_restore_lounge(self) -> None:
        """Test case for restore_lounge

        Restore Lounge
        """
        pass

    def test_update_lounge(self) -> None:
        """Test case for update_lounge

        Update Lounge
        """
        pass


if __name__ == '__main__':
    unittest.main()
