# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-13T14:13:26.279Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.dining_api import DiningApi


class TestDiningApi(unittest.TestCase):
    """DiningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiningApi()

    def tearDown(self) -> None:
        pass

    def test_archive_dining(self) -> None:
        """Test case for archive_dining

        Archive Dining info
        """
        pass

    def test_create_dining(self) -> None:
        """Test case for create_dining

        Create Dining info
        """
        pass

    def test_fetch_all_dining(self) -> None:
        """Test case for fetch_all_dining

        Get all Dining info
        """
        pass

    def test_restore_dining(self) -> None:
        """Test case for restore_dining

        Restore Dining info
        """
        pass

    def test_update_dining(self) -> None:
        """Test case for update_dining

        Update Dining info
        """
        pass


if __name__ == '__main__':
    unittest.main()
