# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-06T22:37:39.158Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wtsms_update_phone_number_config import WTSMSUpdatePhoneNumberConfig

class TestWTSMSUpdatePhoneNumberConfig(unittest.TestCase):
    """WTSMSUpdatePhoneNumberConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTSMSUpdatePhoneNumberConfig:
        """Test WTSMSUpdatePhoneNumberConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTSMSUpdatePhoneNumberConfig`
        """
        model = WTSMSUpdatePhoneNumberConfig()
        if include_optional:
            return WTSMSUpdatePhoneNumberConfig(
                company_name = Wallet Inc,
                privacy_policy_url = https://example.com/privacy-policy,
                terms_of_service_url = https://example.com/terms-of-service,
                message_footer = Info message from Wallet Inc,
                stop_response = Sorry to see you go,
                help_response = How can we help you?,
                help_desk_keyword = HELPME,
                help_desk_queue_response = How can we help you?,
                is_connected_to_watson = None,
                watson_username = None,
                watson_password = None,
                watson_conversation_workplace_id = None
            )
        else:
            return WTSMSUpdatePhoneNumberConfig(
                company_name = Wallet Inc,
                message_footer = Info message from Wallet Inc,
                stop_response = Sorry to see you go,
                help_response = How can we help you?,
                help_desk_keyword = HELPME,
                help_desk_queue_response = How can we help you?,
        )
        """

    def testWTSMSUpdatePhoneNumberConfig(self):
        """Test WTSMSUpdatePhoneNumberConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
