# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.2.4**, built 2026-07-06T11:10:43.561Z

    The version of the OpenAPI document: 2.2.4
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.business_type import BusinessType

class TestBusinessType(unittest.TestCase):
    """BusinessType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessType(self):
        """Test BusinessType"""
        # inst = BusinessType()

if __name__ == '__main__':
    unittest.main()
