# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-13T18:42:31.067Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.stripe_connect_api import StripeConnectApi


class TestStripeConnectApi(unittest.TestCase):
    """StripeConnectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StripeConnectApi()

    def tearDown(self) -> None:
        pass

    def test_create_connect_onboarding_link(self) -> None:
        """Test case for create_connect_onboarding_link

        Create a Stripe Connect onboarding link Creates the merchant's STANDARD connected account on first call (pass-through model; the merchant owns their Stripe relationship) and returns a hosted onboarding link (single-use, expiring). returnUrl/refreshUrl are validated against the origin allowlist. Not a fund-moving write; 403 when the merchant's plan does not include Connect ecommerce.
        """
        pass

    def test_fetch_connect_account_status(self) -> None:
        """Test case for fetch_connect_account_status

        Get Stripe Connect account status Observability for Flow B ecommerce: the connected-account id and capability flags for the authenticated merchant, plus the derived onboarding status and the server-side ecommerce eligibility flag. Returns the defined not-started shape (accountId null) rather than 404 when onboarding has not begun.
        """
        pass

    def test_fetch_connect_payments_summary(self) -> None:
        """Test case for fetch_connect_payments_summary

        Get a read-only Connect payments summary Balances, recent payouts, and recent charges (up to 10 each) for the merchant's connected account, in Stripe minor units with currency codes. Read-only observability; Wallet is not in the Flow B money path.
        """
        pass


if __name__ == '__main__':
    unittest.main()
