# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T10:12:05.931Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_dynamic_voucher_redemption import WTDynamicVoucherRedemption

class TestWTDynamicVoucherRedemption(unittest.TestCase):
    """WTDynamicVoucherRedemption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTDynamicVoucherRedemption:
        """Test WTDynamicVoucherRedemption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTDynamicVoucherRedemption`
        """
        model = WTDynamicVoucherRedemption()
        if include_optional:
            return WTDynamicVoucherRedemption(
                session_key = AN-47,
                redeemed_amount = 250,
                dynamic_voucher_id = 'ueJDL982Hs',
                redeemed_source = AN-47,
                redeemed_transaction_id = Jqkaurn28170dh1fh,
                transaction_type = redemption,
                register_id = jdu74hsy,
                id = jdu37eua98,
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                redeemed_at = 2016-06-22 19:10:25-07,
                refunded_at = 2016-06-22 20:10:25-07,
                refunded_transaction_id = Jqkaurn28170dh1fh,
                refunded_amount = 540,
                status = created,
                redeemed_amount_decimal = 5.00,
                redeemed_amount_string = $5.00,
                discount_received = None,
                meta_value = None,
                parent_object_id = 'ueJDL982Hs'
            )
        else:
            return WTDynamicVoucherRedemption(
                session_key = AN-47,
                redeemed_amount = 250,
                dynamic_voucher_id = 'ueJDL982Hs',
                redeemed_source = AN-47,
                redeemed_transaction_id = Jqkaurn28170dh1fh,
                transaction_type = redemption,
                register_id = jdu74hsy,
                id = jdu37eua98,
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                refunded_transaction_id = Jqkaurn28170dh1fh,
                refunded_amount = 540,
                status = created,
                redeemed_amount_decimal = 5.00,
                redeemed_amount_string = $5.00,
                discount_received = None,
                meta_value = None,
                parent_object_id = 'ueJDL982Hs',
        )
        """

    def testWTDynamicVoucherRedemption(self):
        """Test WTDynamicVoucherRedemption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
