# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-09T11:20:36.694Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.sort_direction import SortDirection

class TestSortDirection(unittest.TestCase):
    """SortDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortDirection(self):
        """Test SortDirection"""
        # inst = SortDirection()

if __name__ == '__main__':
    unittest.main()
