# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T09:49:03.606Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.pick_ss_opt_in_list_member_update_params_exclude_keyof_ss_opt_in_list_member_update_params_merchant_created_at_or_max_sms_count import PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount

class TestPickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount(unittest.TestCase):
    """PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount:
        """Test PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount`
        """
        model = PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount()
        if include_optional:
            return PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount(
                caller_name = 'JOHN DOE',
                caller_type = 'CONSUMER',
                opt_in_list_id = '0123456789',
                opt_in_source_id = AGST63udhv,
                is_subscribed = True,
                is_pending_age21_verification = True,
                mobile_phone_number = '+18047552674',
                referring_url = 'https://example.com/referring-url'
            )
        else:
            return PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount(
                opt_in_list_id = '0123456789',
                opt_in_source_id = AGST63udhv,
                is_subscribed = True,
                is_pending_age21_verification = True,
                mobile_phone_number = '+18047552674',
                referring_url = 'https://example.com/referring-url',
        )
        """

    def testPickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount(self):
        """Test PickSSOptInListMemberUpdateParamsExcludeKeyofSSOptInListMemberUpdateParamsMerchantCreatedAtOrMaxSMSCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
