"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.wt_gaming_create_params import WTGamingCreateParams


class TestWTGamingCreateParams(unittest.TestCase):
    """WTGamingCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWTGamingCreateParams(self):
        """Test WTGamingCreateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WTGamingCreateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
