# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T11:10:05.370Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wtqr_code_design_update_params import WTQRCodeDesignUpdateParams

class TestWTQRCodeDesignUpdateParams(unittest.TestCase):
    """WTQRCodeDesignUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTQRCodeDesignUpdateParams:
        """Test WTQRCodeDesignUpdateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTQRCodeDesignUpdateParams`
        """
        model = WTQRCodeDesignUpdateParams()
        if include_optional:
            return WTQRCodeDesignUpdateParams(
                name = This is the name of the design,
                serialized_json_configuration = None,
                serialized_json_border = None
            )
        else:
            return WTQRCodeDesignUpdateParams(
                name = This is the name of the design,
                serialized_json_configuration = None,
        )
        """

    def testWTQRCodeDesignUpdateParams(self):
        """Test WTQRCodeDesignUpdateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
