# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.2**, built 2026-07-08T16:57:46.002Z

    The version of the OpenAPI document: 2.3.2
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_authentication_check_session_token_status_response import WTAuthenticationCheckSessionTokenStatusResponse

class TestWTAuthenticationCheckSessionTokenStatusResponse(unittest.TestCase):
    """WTAuthenticationCheckSessionTokenStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTAuthenticationCheckSessionTokenStatusResponse:
        """Test WTAuthenticationCheckSessionTokenStatusResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTAuthenticationCheckSessionTokenStatusResponse`
        """
        model = WTAuthenticationCheckSessionTokenStatusResponse()
        if include_optional:
            return WTAuthenticationCheckSessionTokenStatusResponse(
                status = Valid
            )
        else:
            return WTAuthenticationCheckSessionTokenStatusResponse(
                status = Valid,
        )
        """

    def testWTAuthenticationCheckSessionTokenStatusResponse(self):
        """Test WTAuthenticationCheckSessionTokenStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
