# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-11T12:34:10.651Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.qr_code_designs_api import QRCodeDesignsApi


class TestQRCodeDesignsApi(unittest.TestCase):
    """QRCodeDesignsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QRCodeDesignsApi()

    def tearDown(self) -> None:
        pass

    def test_archive_qr_code_design(self) -> None:
        """Test case for archive_qr_code_design

        Archive QR Code Design
        """
        pass

    def test_create_qr_code_design(self) -> None:
        """Test case for create_qr_code_design

        Create QR Code design
        """
        pass

    def test_fetch_all_qr_code_designs(self) -> None:
        """Test case for fetch_all_qr_code_designs

        Get all QR Code Designs
        """
        pass

    def test_fetch_qr_code_design_by_id(self) -> None:
        """Test case for fetch_qr_code_design_by_id

        Get QR Code Design
        """
        pass

    def test_restore_qr_code_design(self) -> None:
        """Test case for restore_qr_code_design

        Restore QR Code Design
        """
        pass

    def test_update_qr_code_design(self) -> None:
        """Test case for update_qr_code_design

        Update QR Code Design
        """
        pass


if __name__ == '__main__':
    unittest.main()
