# coding: utf-8

"""
    wallet-api

    API

    The version of the OpenAPI document: 2.1.600
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.set_default_payment_method_request import SetDefaultPaymentMethodRequest

class TestSetDefaultPaymentMethodRequest(unittest.TestCase):
    """SetDefaultPaymentMethodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetDefaultPaymentMethodRequest:
        """Test SetDefaultPaymentMethodRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetDefaultPaymentMethodRequest`
        """
        model = SetDefaultPaymentMethodRequest()
        if include_optional:
            return SetDefaultPaymentMethodRequest(
                payment_method_id = ''
            )
        else:
            return SetDefaultPaymentMethodRequest(
                payment_method_id = '',
        )
        """

    def testSetDefaultPaymentMethodRequest(self):
        """Test SetDefaultPaymentMethodRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
