# coding: utf-8

"""
    wallet-api

    API

    The version of the OpenAPI document: 2.1.600
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.fetch_opt_in_list_subscribers_by_page200_response import FetchOptInListSubscribersByPage200Response

class TestFetchOptInListSubscribersByPage200Response(unittest.TestCase):
    """FetchOptInListSubscribersByPage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchOptInListSubscribersByPage200Response:
        """Test FetchOptInListSubscribersByPage200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchOptInListSubscribersByPage200Response`
        """
        model = FetchOptInListSubscribersByPage200Response()
        if include_optional:
            return FetchOptInListSubscribersByPage200Response(
                total = 1.337,
                length = 1.337,
                results = [
                    wallet.models.opt_in_list_subscriber.OptInListSubscriber(
                        caller_name = 'JOHN DOE', 
                        caller_type = 'CONSUMER', 
                        opt_in_list_id = 'C0123456789', 
                        opt_in_source_id = AGST63udhv, 
                        is_subscribed = True, 
                        is_pending_age21_verification = True, 
                        mobile_phone_number = '+18047552674', 
                        referring_url = 'https://example.com/referring-url', 
                        id = jdu37eua98, 
                        merchant_id = 'C0123456789', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        opted_status = True, 
                        source = wallet.models.ss_opt_in_source.SSOptInSource(
                            id = 'jdu37eua98', 
                            list_id = 'C0123456789', 
                            source_name = 'Christmas Sales', 
                            employee_id = 'C0123456789', 
                            merchant_id = 'C0123456789', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            is_active = True, ), )
                    ]
            )
        else:
            return FetchOptInListSubscribersByPage200Response(
                total = 1.337,
                length = 1.337,
                results = [
                    wallet.models.opt_in_list_subscriber.OptInListSubscriber(
                        caller_name = 'JOHN DOE', 
                        caller_type = 'CONSUMER', 
                        opt_in_list_id = 'C0123456789', 
                        opt_in_source_id = AGST63udhv, 
                        is_subscribed = True, 
                        is_pending_age21_verification = True, 
                        mobile_phone_number = '+18047552674', 
                        referring_url = 'https://example.com/referring-url', 
                        id = jdu37eua98, 
                        merchant_id = 'C0123456789', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        opted_status = True, 
                        source = wallet.models.ss_opt_in_source.SSOptInSource(
                            id = 'jdu37eua98', 
                            list_id = 'C0123456789', 
                            source_name = 'Christmas Sales', 
                            employee_id = 'C0123456789', 
                            merchant_id = 'C0123456789', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            is_active = True, ), )
                    ],
        )
        """

    def testFetchOptInListSubscribersByPage200Response(self):
        """Test FetchOptInListSubscribersByPage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
