"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.message_direction_any_of import MessageDirectionAnyOf


class TestMessageDirectionAnyOf(unittest.TestCase):
    """MessageDirectionAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageDirectionAnyOf(self):
        """Test MessageDirectionAnyOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageDirectionAnyOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
