# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T17:06:57.691Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.ms_merchant_credit_history import MSMerchantCreditHistory

class TestMSMerchantCreditHistory(unittest.TestCase):
    """MSMerchantCreditHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MSMerchantCreditHistory:
        """Test MSMerchantCreditHistory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MSMerchantCreditHistory`
        """
        model = MSMerchantCreditHistory()
        if include_optional:
            return MSMerchantCreditHistory(
                member_identifier = 1hdue82,
                mobile_number = +18047552674,
                credit_amount = 125,
                id = 35022c6b-d78d-48af-aee3-2355b465d304,
                merchant_credit_id = 'ueJDL982Hs',
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                is_active = true
            )
        else:
            return MSMerchantCreditHistory(
                mobile_number = +18047552674,
                credit_amount = 125,
                id = 35022c6b-d78d-48af-aee3-2355b465d304,
                merchant_credit_id = 'ueJDL982Hs',
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                is_active = true,
        )
        """

    def testMSMerchantCreditHistory(self):
        """Test MSMerchantCreditHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
