"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.533
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import unittest

import wallet
from wallet.api.virtual_business_card_api import VirtualBusinessCardApi  # noqa: E501


class TestVirtualBusinessCardApi(unittest.TestCase):
    """VirtualBusinessCardApi unit test stubs"""

    def setUp(self):
        self.api = VirtualBusinessCardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_virtual_business_card(self):
        """Test case for archive_virtual_business_card

        Archive VirtualBusinessCard  # noqa: E501
        """
        pass

    def test_create_virtual_business_card(self):
        """Test case for create_virtual_business_card

        Create VirtualBusinessCard  # noqa: E501
        """
        pass

    def test_fetch_all_virtual_business_cards(self):
        """Test case for fetch_all_virtual_business_cards

        Fetch all VirtualBusinessCards  # noqa: E501
        """
        pass

    def test_fetch_virtual_business_card(self):
        """Test case for fetch_virtual_business_card

        Fetch virtual business card  # noqa: E501
        """
        pass

    def test_fetch_virtual_business_card_requests(self):
        """Test case for fetch_virtual_business_card_requests

        Fetch requests  # noqa: E501
        """
        pass

    def test_restore_virtual_business_card(self):
        """Test case for restore_virtual_business_card

        Restore VirtualBusinessCard  # noqa: E501
        """
        pass

    def test_update_virtual_business_card(self):
        """Test case for update_virtual_business_card

        Update VirtualBusinessCard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
