# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.7.3**, built 2026-07-14T04:37:03.852Z

    The version of the OpenAPI document: 2.7.3
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_archive_service(self) -> None:
        """Test case for archive_service

        Archive Service
        """
        pass

    def test_create_service(self) -> None:
        """Test case for create_service

        Create Service
        """
        pass

    def test_fetch_all_services(self) -> None:
        """Test case for fetch_all_services

        Get all Services
        """
        pass

    def test_restore_service(self) -> None:
        """Test case for restore_service

        Restore Service
        """
        pass

    def test_update_service(self) -> None:
        """Test case for update_service

        Update Service
        """
        pass


if __name__ == '__main__':
    unittest.main()
