# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T15:21:44.764Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_dining_create_params import WTDiningCreateParams

class TestWTDiningCreateParams(unittest.TestCase):
    """WTDiningCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTDiningCreateParams:
        """Test WTDiningCreateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTDiningCreateParams`
        """
        model = WTDiningCreateParams()
        if include_optional:
            return WTDiningCreateParams(
                title = This is the title of the dining option,
                description = This is the description of the dining option,
                displayed_price = $200-$350,
                order_number = 1,
                media_url = 'https://wall.et/media/H847Sjudbw.png',
                additional_info_url = https://your-site.com/restaurants/steak-house
            )
        else:
            return WTDiningCreateParams(
                title = This is the title of the dining option,
                description = This is the description of the dining option,
                order_number = 1,
        )
        """

    def testWTDiningCreateParams(self):
        """Test WTDiningCreateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
