# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T18:16:04.538Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.import_export_api import ImportExportApi


class TestImportExportApi(unittest.TestCase):
    """ImportExportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportExportApi()

    def tearDown(self) -> None:
        pass

    def test_export_club_members(self) -> None:
        """Test case for export_club_members

        Export club members
        """
        pass

    def test_export_merchant_credits(self) -> None:
        """Test case for export_merchant_credits

        Export merchant credits
        """
        pass

    def test_export_static_voucher_campaign(self) -> None:
        """Test case for export_static_voucher_campaign

        Export static voucher campaign
        """
        pass

    def test_import_club_members(self) -> None:
        """Test case for import_club_members

        Import club members
        """
        pass

    def test_import_merchant_credits(self) -> None:
        """Test case for import_merchant_credits

        Import merchant credits
        """
        pass

    def test_set_export_data_files_read(self) -> None:
        """Test case for set_export_data_files_read

        Mark export data files as read
        """
        pass

    def test_update_club_members(self) -> None:
        """Test case for update_club_members

        Update club members
        """
        pass


if __name__ == '__main__':
    unittest.main()
