# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.1.604**, built 2026-07-06T17:18:29.852Z

    The version of the OpenAPI document: 2.1.604
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_advertisement_credit_create_params import WTAdvertisementCreditCreateParams

class TestWTAdvertisementCreditCreateParams(unittest.TestCase):
    """WTAdvertisementCreditCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTAdvertisementCreditCreateParams:
        """Test WTAdvertisementCreditCreateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTAdvertisementCreditCreateParams`
        """
        model = WTAdvertisementCreditCreateParams()
        if include_optional:
            return WTAdvertisementCreditCreateParams(
                title = 'Ad Credit Title',
                value_type = percent,
                payment_design_id = 'ueJDL982Hs',
                max_uses = 250,
                discount_value = 250
            )
        else:
            return WTAdvertisementCreditCreateParams(
                title = 'Ad Credit Title',
                value_type = percent,
                payment_design_id = 'ueJDL982Hs',
                max_uses = 250,
                discount_value = 250,
        )
        """

    def testWTAdvertisementCreditCreateParams(self):
        """Test WTAdvertisementCreditCreateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
