# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.3**, built 2026-07-09T22:41:33.079Z

    The version of the OpenAPI document: 2.4.3
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_dynamic_voucher_update_params import WTDynamicVoucherUpdateParams

class TestWTDynamicVoucherUpdateParams(unittest.TestCase):
    """WTDynamicVoucherUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTDynamicVoucherUpdateParams:
        """Test WTDynamicVoucherUpdateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTDynamicVoucherUpdateParams`
        """
        model = WTDynamicVoucherUpdateParams()
        if include_optional:
            return WTDynamicVoucherUpdateParams(
                title = 'Thanksgiving Marketing Campaign',
                notes = 'This is a marketing campaign that needs to be run during the Thanksgiving week',
                payment_design_id = 'ueJDL982Hs',
                date_time_start = '2016-06-22 19:10:25-07',
                date_time_expiration = '2016-06-22 19:10:25-07',
                starting_value = 250,
                max_budget = 5000,
                decrease_amount = 10,
                frequency = 15,
                frequency_type = Minute(s),
                decrease_by = 1.337,
                decrease_every = 1.337
            )
        else:
            return WTDynamicVoucherUpdateParams(
                title = 'Thanksgiving Marketing Campaign',
                notes = 'This is a marketing campaign that needs to be run during the Thanksgiving week',
                payment_design_id = 'ueJDL982Hs',
                date_time_start = '2016-06-22 19:10:25-07',
                date_time_expiration = '2016-06-22 19:10:25-07',
                starting_value = 250,
                max_budget = 5000,
                decrease_amount = 10,
                frequency = 15,
                frequency_type = Minute(s),
        )
        """

    def testWTDynamicVoucherUpdateParams(self):
        """Test WTDynamicVoucherUpdateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
