"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import wallet
from wallet.model.merchant_id import MerchantID
globals()['MerchantID'] = MerchantID
from wallet.model.amenity import Amenity


class TestAmenity(unittest.TestCase):
    """Amenity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAmenity(self):
        """Test Amenity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Amenity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
