# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T03:43:13.036Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_connect_requirements import WTConnectRequirements

class TestWTConnectRequirements(unittest.TestCase):
    """WTConnectRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTConnectRequirements:
        """Test WTConnectRequirements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTConnectRequirements`
        """
        model = WTConnectRequirements()
        if include_optional:
            return WTConnectRequirements(
                currently_due = None,
                past_due = None,
                eventually_due = None,
                pending_verification = None,
                disabled_reason = None
            )
        else:
            return WTConnectRequirements(
                currently_due = None,
                past_due = None,
                eventually_due = None,
                pending_verification = None,
        )
        """

    def testWTConnectRequirements(self):
        """Test WTConnectRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
