# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T04:24:40.846Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.billing_payments_api import BillingPaymentsApi


class TestBillingPaymentsApi(unittest.TestCase):
    """BillingPaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingPaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_buy_add_on(self) -> None:
        """Test case for buy_add_on

        Buy add-on product
        """
        pass

    def test_buy_special_offer(self) -> None:
        """Test case for buy_special_offer

        Buy special offer
        """
        pass

    def test_cancel_plan(self) -> None:
        """Test case for cancel_plan

        Cancel billing plan
        """
        pass

    def test_change_plan(self) -> None:
        """Test case for change_plan

        Change billing plan
        """
        pass

    def test_create_billing_portal_session(self) -> None:
        """Test case for create_billing_portal_session

        Create a Stripe Billing Portal session
        """
        pass

    def test_fetch_add_ons(self) -> None:
        """Test case for fetch_add_ons

        Get add-on products
        """
        pass

    def test_fetch_customer_payment_methods(self) -> None:
        """Test case for fetch_customer_payment_methods

        Get payment methods
        """
        pass

    def test_fetch_industry(self) -> None:
        """Test case for fetch_industry

        Get merchant's industry
        """
        pass

    def test_fetch_invoices(self) -> None:
        """Test case for fetch_invoices

        Get invoices
        """
        pass

    def test_fetch_special_offers(self) -> None:
        """Test case for fetch_special_offers

        Get special offers
        """
        pass

    def test_fetch_subscription(self) -> None:
        """Test case for fetch_subscription

        Get subscription
        """
        pass

    def test_fetch_usage_summary(self) -> None:
        """Test case for fetch_usage_summary

        Get usage summary
        """
        pass

    def test_run_financing_soft_pull(self) -> None:
        """Test case for run_financing_soft_pull

        Run a consumer-authorized financing soft credit inquiry (LeadFi, tri-bureau) Consumer-initiated FCRA permissible purpose: the authenticated user explicitly authorizes the check (disclosure text is submitted verbatim and persisted as evidence). The consent IP is captured server-side from the request; the inquiry is refused when it cannot be captured. Fails fast until LeadFi credentials are provisioned (go-live gated on counsel sign-off).
        """
        pass

    def test_save_payment_method(self) -> None:
        """Test case for save_payment_method

        Save payment method
        """
        pass

    def test_set_default_payment_method(self) -> None:
        """Test case for set_default_payment_method

        Set payment method as default
        """
        pass

    def test_upcoming_invoices(self) -> None:
        """Test case for upcoming_invoices

        Get upcoming invoices
        """
        pass

    def test_verify_payment_method(self) -> None:
        """Test case for verify_payment_method

        Verify payment method
        """
        pass


if __name__ == '__main__':
    unittest.main()
