"""
    wallet-api

    API  # noqa: E501

    The version of the OpenAPI document: 2.1.535
    Contact: development@wallet.inc
    Generated by: https://openapi-generator.tech
"""


import unittest

import wallet
from wallet.api.services_api import ServicesApi  # noqa: E501


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self):
        self.api = ServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_service(self):
        """Test case for archive_service

        Archive service  # noqa: E501
        """
        pass

    def test_create_service(self):
        """Test case for create_service

        Create service  # noqa: E501
        """
        pass

    def test_fetch_all_services(self):
        """Test case for fetch_all_services

        Fetch all services  # noqa: E501
        """
        pass

    def test_restore_service(self):
        """Test case for restore_service

        Restore service  # noqa: E501
        """
        pass

    def test_update_service(self):
        """Test case for update_service

        Update service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
