# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-13T17:36:00.108Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.static_vouchers_api import StaticVouchersApi


class TestStaticVouchersApi(unittest.TestCase):
    """StaticVouchersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StaticVouchersApi()

    def tearDown(self) -> None:
        pass

    def test_create_static_voucher(self) -> None:
        """Test case for create_static_voucher

        Create Static Voucher
        """
        pass

    def test_delete_static_voucher(self) -> None:
        """Test case for delete_static_voucher

        Delete Static Voucher
        """
        pass

    def test_fetch_reach_stats_of_all_static_vouchers(self) -> None:
        """Test case for fetch_reach_stats_of_all_static_vouchers

        Get reach statistics of all Static Vouchers
        """
        pass

    def test_fetch_reach_stats_of_individual_static_voucher(self) -> None:
        """Test case for fetch_reach_stats_of_individual_static_voucher

        Get reach statistics of a single Static Voucher
        """
        pass

    def test_fetch_static_voucher(self) -> None:
        """Test case for fetch_static_voucher

        Get Static Voucher
        """
        pass

    def test_update_static_voucher(self) -> None:
        """Test case for update_static_voucher

        Update Static Voucher
        """
        pass


if __name__ == '__main__':
    unittest.main()
