# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T21:13:51.937Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_prize_promotion_create_params import WTPrizePromotionCreateParams

class TestWTPrizePromotionCreateParams(unittest.TestCase):
    """WTPrizePromotionCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTPrizePromotionCreateParams:
        """Test WTPrizePromotionCreateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTPrizePromotionCreateParams`
        """
        model = WTPrizePromotionCreateParams()
        if include_optional:
            return WTPrizePromotionCreateParams(
                game_type = None,
                title = Spin & Win July,
                win_odds = 0.2,
                prize_tiers = None,
                per_guest_play_limit = 1,
                play_limit_period = None,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                trigger_type = None,
                minimum_age = None,
                registration_attested = True
            )
        else:
            return WTPrizePromotionCreateParams(
                game_type = None,
                title = Spin & Win July,
                win_odds = 0.2,
                prize_tiers = None,
                per_guest_play_limit = 1,
                play_limit_period = None,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                trigger_type = None,
        )
        """

    def testWTPrizePromotionCreateParams(self):
        """Test WTPrizePromotionCreateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
