# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T15:40:46.402Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.api.customer_api import CustomerApi


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_active_vouchers(self) -> None:
        """Test case for fetch_active_vouchers

        Get active static vouchers
        """
        pass

    def test_fetch_all_vouchers(self) -> None:
        """Test case for fetch_all_vouchers

        Get all static vouchers
        """
        pass

    def test_fetch_expired_vouchers(self) -> None:
        """Test case for fetch_expired_vouchers

        Get expired static vouchers
        """
        pass

    def test_fetch_redeemed_vouchers(self) -> None:
        """Test case for fetch_redeemed_vouchers

        Get redeemed static vouchers
        """
        pass

    def test_fetch_refunded_vouchers(self) -> None:
        """Test case for fetch_refunded_vouchers

        Get refunded static vouchers
        """
        pass

    def test_fetch_upcoming_vouchers(self) -> None:
        """Test case for fetch_upcoming_vouchers

        Get upcoming static vouchers
        """
        pass

    def test_fetch_wallet_views_for_session(self) -> None:
        """Test case for fetch_wallet_views_for_session

        Get Wallet Views for Session
        """
        pass

    def test_search_by_member_id(self) -> None:
        """Test case for search_by_member_id

        Find members with memberID
        """
        pass

    def test_search_by_phone_number(self) -> None:
        """Test case for search_by_phone_number

        Find members with phone number
        """
        pass


if __name__ == '__main__':
    unittest.main()
