# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-12T13:05:00.071Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_message_instance import WTMessageInstance

class TestWTMessageInstance(unittest.TestCase):
    """WTMessageInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTMessageInstance:
        """Test WTMessageInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTMessageInstance`
        """
        model = WTMessageInstance()
        if include_optional:
            return WTMessageInstance(
            )
        else:
            return WTMessageInstance(
        )
        """

    def testWTMessageInstance(self):
        """Test WTMessageInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
