# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.2.7**, built 2026-07-06T16:46:16.045Z

    The version of the OpenAPI document: 2.2.7
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_merchant_credit import WTMerchantCredit

class TestWTMerchantCredit(unittest.TestCase):
    """WTMerchantCredit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTMerchantCredit:
        """Test WTMerchantCredit
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTMerchantCredit`
        """
        model = WTMerchantCredit()
        if include_optional:
            return WTMerchantCredit(
                id = 'CMueJDL982Hs',
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                mobile_number = +18047552674,
                credit_amount = 125,
                member_id = 1hdue82,
                credit_amount_decimal = 1250.52,
                credit_amount_string = 1,250.52
            )
        else:
            return WTMerchantCredit(
                id = 'CMueJDL982Hs',
                merchant_id = 'ueJDL982Hs',
                created_at = 2016-06-22 19:10:25-07,
                updated_at = 2016-06-22 19:10:25-07,
                is_active = true,
                mobile_number = +18047552674,
                credit_amount = 125,
                credit_amount_decimal = 1250.52,
                credit_amount_string = 1,250.52,
        )
        """

    def testWTMerchantCredit(self):
        """Test WTMerchantCredit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
