# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.7.1**, built 2026-07-14T02:00:08.523Z

    The version of the OpenAPI document: 2.7.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.business_stock_exchanges import BusinessStockExchanges

class TestBusinessStockExchanges(unittest.TestCase):
    """BusinessStockExchanges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessStockExchanges(self):
        """Test BusinessStockExchanges"""
        # inst = BusinessStockExchanges()

if __name__ == '__main__':
    unittest.main()
