# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.3.1**, built 2026-07-07T21:13:51.937Z

    The version of the OpenAPI document: 2.3.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wallet.models.wt_prize_promotion import WTPrizePromotion

class TestWTPrizePromotion(unittest.TestCase):
    """WTPrizePromotion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WTPrizePromotion:
        """Test WTPrizePromotion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WTPrizePromotion`
        """
        model = WTPrizePromotion()
        if include_optional:
            return WTPrizePromotion(
                game_type = None,
                title = Spin & Win July,
                win_odds = 0.2,
                prize_tiers = None,
                per_guest_play_limit = 1,
                play_limit_period = None,
                start_date = None,
                end_date = None,
                trigger_type = None,
                minimum_age = None,
                registration_attested = None,
                id = None,
                merchant_id = None,
                is_active = None,
                total_prize_pool_value = None,
                odds_disclosure = None
            )
        else:
            return WTPrizePromotion(
                game_type = None,
                title = Spin & Win July,
                win_odds = 0.2,
                prize_tiers = None,
                per_guest_play_limit = 1,
                play_limit_period = None,
                start_date = None,
                end_date = None,
                trigger_type = None,
                id = None,
                merchant_id = None,
                is_active = None,
                total_prize_pool_value = None,
                odds_disclosure = None,
        )
        """

    def testWTPrizePromotion(self):
        """Test WTPrizePromotion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
