# coding: utf-8

"""
    wallet-api

    API

    The version of the OpenAPI document: 2.2.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from wallet.models.pick_vs_static_voucher_exclude_keyof_vs_static_voucher_redeemed_at_or_refunded_at_or_last_viewed_at_register_id import PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID
from wallet.models.pick_vs_static_voucher_exclude_keyof_vs_static_voucher_redeemed_at_or_refunded_at_or_last_viewed_at_transaction_type import PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtTransactionType
from wallet.models.static_voucher_id import StaticVoucherId
from wallet.models.status import Status
from typing import Optional, Set
from typing_extensions import Self

class AdvertisementCreditScan(BaseModel):
    """
    AdvertisementCreditScan
    """ # noqa: E501
    id: StaticVoucherId
    transaction_type: PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtTransactionType = Field(alias="transactionType")
    register_id: PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID = Field(alias="registerID")
    redeemed_source: StrictStr = Field(alias="redeemedSource")
    redeemed_transaction_id: StrictStr = Field(alias="redeemedTransactionID")
    redeemed_amount: Annotated[int, Field(strict=True, ge=0)] = Field(alias="redeemedAmount")
    is_redeemed: StrictBool = Field(alias="isRedeemed")
    refunded_transaction_id: StrictStr = Field(alias="refundedTransactionID")
    refunded_amount: Annotated[int, Field(strict=True, ge=0)] = Field(alias="refundedAmount")
    status: Status
    authorized_against_check_number: StrictStr = Field(alias="authorizedAgainstCheckNumber")
    authorized_amount: Annotated[int, Field(strict=True, ge=0)] = Field(alias="authorizedAmount")
    merchant_id: Annotated[str, Field(min_length=10, strict=True, max_length=10)] = Field(alias="merchantID")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    is_active: StrictBool = Field(alias="isActive")
    advertisement_credit_id: Annotated[str, Field(min_length=10, strict=True, max_length=10)] = Field(alias="advertisementCreditID")
    redeemed_amount_decimal: Optional[Any] = Field(alias="redeemedAmount_decimal")
    redeemed_amount_string: Optional[Any] = Field(alias="redeemedAmount_string")
    authorized_amount_decimal: Optional[Any] = Field(alias="authorizedAmount_decimal")
    authorized_amount_string: Optional[Any] = Field(alias="authorizedAmount_string")
    date_time_redeemed: Optional[Any] = Field(alias="dateTimeRedeemed")
    date_time_refunded: Optional[Any] = Field(alias="dateTimeRefunded")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "transactionType", "registerID", "redeemedSource", "redeemedTransactionID", "redeemedAmount", "isRedeemed", "refundedTransactionID", "refundedAmount", "status", "authorizedAgainstCheckNumber", "authorizedAmount", "merchantID", "createdAt", "updatedAt", "isActive", "advertisementCreditID", "redeemedAmount_decimal", "redeemedAmount_string", "authorizedAmount_decimal", "authorizedAmount_string", "dateTimeRedeemed", "dateTimeRefunded"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvertisementCreditScan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction_type
        if self.transaction_type:
            _dict['transactionType'] = self.transaction_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of register_id
        if self.register_id:
            _dict['registerID'] = self.register_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if redeemed_amount_decimal (nullable) is None
        # and model_fields_set contains the field
        if self.redeemed_amount_decimal is None and "redeemed_amount_decimal" in self.model_fields_set:
            _dict['redeemedAmount_decimal'] = None

        # set to None if redeemed_amount_string (nullable) is None
        # and model_fields_set contains the field
        if self.redeemed_amount_string is None and "redeemed_amount_string" in self.model_fields_set:
            _dict['redeemedAmount_string'] = None

        # set to None if authorized_amount_decimal (nullable) is None
        # and model_fields_set contains the field
        if self.authorized_amount_decimal is None and "authorized_amount_decimal" in self.model_fields_set:
            _dict['authorizedAmount_decimal'] = None

        # set to None if authorized_amount_string (nullable) is None
        # and model_fields_set contains the field
        if self.authorized_amount_string is None and "authorized_amount_string" in self.model_fields_set:
            _dict['authorizedAmount_string'] = None

        # set to None if date_time_redeemed (nullable) is None
        # and model_fields_set contains the field
        if self.date_time_redeemed is None and "date_time_redeemed" in self.model_fields_set:
            _dict['dateTimeRedeemed'] = None

        # set to None if date_time_refunded (nullable) is None
        # and model_fields_set contains the field
        if self.date_time_refunded is None and "date_time_refunded" in self.model_fields_set:
            _dict['dateTimeRefunded'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvertisementCreditScan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": StaticVoucherId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "transactionType": PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtTransactionType.from_dict(obj["transactionType"]) if obj.get("transactionType") is not None else None,
            "registerID": PickVSStaticVoucherExcludeKeyofVSStaticVoucherRedeemedAtOrRefundedAtOrLastViewedAtRegisterID.from_dict(obj["registerID"]) if obj.get("registerID") is not None else None,
            "redeemedSource": obj.get("redeemedSource"),
            "redeemedTransactionID": obj.get("redeemedTransactionID"),
            "redeemedAmount": obj.get("redeemedAmount"),
            "isRedeemed": obj.get("isRedeemed"),
            "refundedTransactionID": obj.get("refundedTransactionID"),
            "refundedAmount": obj.get("refundedAmount"),
            "status": Status.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "authorizedAgainstCheckNumber": obj.get("authorizedAgainstCheckNumber"),
            "authorizedAmount": obj.get("authorizedAmount"),
            "merchantID": obj.get("merchantID"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "isActive": obj.get("isActive"),
            "advertisementCreditID": obj.get("advertisementCreditID"),
            "redeemedAmount_decimal": obj.get("redeemedAmount_decimal"),
            "redeemedAmount_string": obj.get("redeemedAmount_string"),
            "authorizedAmount_decimal": obj.get("authorizedAmount_decimal"),
            "authorizedAmount_string": obj.get("authorizedAmount_string"),
            "dateTimeRedeemed": obj.get("dateTimeRedeemed"),
            "dateTimeRefunded": obj.get("dateTimeRefunded")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


