# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.44.0**, built 2026-09-01T13:15:47.228Z

    The version of the OpenAPI document: 2.44.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BusinessIndustryGOVERNMENT(str, Enum):
    """
    BusinessIndustryGOVERNMENT
    """

    """
    allowed enum values
    """
    GOVERNMENT = 'GOVERNMENT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BusinessIndustryGOVERNMENT from a JSON string"""
        return cls(json.loads(json_str))


