# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.20.2**, built 2026-07-30T15:18:55.586Z

    The version of the OpenAPI document: 2.20.2
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BusinessTypeNonProfit(str, Enum):
    """
    BusinessTypeNonProfit
    """

    """
    allowed enum values
    """
    NON_MINUS_PROFIT_CORPORATION = 'Non-profit Corporation'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BusinessTypeNonProfit from a JSON string"""
        return cls(json.loads(json_str))


