# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.16.1**, built 2026-07-24T12:19:26.314Z

    The version of the OpenAPI document: 2.16.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from wallet.models.amenity_id import AmenityId
from typing import Optional, Set
from typing_extensions import Self

class Lounge(BaseModel):
    """
    Lounge
    """ # noqa: E501
    title: Optional[Any]
    description: Optional[Any]
    displayed_price: Optional[Any] = Field(default=None, alias="displayedPrice")
    order_number: Optional[Any] = Field(alias="orderNumber")
    media_url: Optional[Any] = Field(default=None, alias="mediaURL")
    additional_info_url: Optional[Any] = Field(default=None, alias="additionalInfoURL")
    id: AmenityId
    created_at: Optional[Any] = Field(alias="createdAt")
    updated_at: Optional[Any] = Field(alias="updatedAt")
    is_active: Optional[Any] = Field(alias="isActive")
    merchant_id: Annotated[str, Field(min_length=10, strict=True, max_length=10)] = Field(alias="merchantID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["title", "description", "displayedPrice", "orderNumber", "mediaURL", "additionalInfoURL", "id", "createdAt", "updatedAt", "isActive", "merchantID"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Lounge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if displayed_price (nullable) is None
        # and model_fields_set contains the field
        if self.displayed_price is None and "displayed_price" in self.model_fields_set:
            _dict['displayedPrice'] = None

        # set to None if order_number (nullable) is None
        # and model_fields_set contains the field
        if self.order_number is None and "order_number" in self.model_fields_set:
            _dict['orderNumber'] = None

        # set to None if media_url (nullable) is None
        # and model_fields_set contains the field
        if self.media_url is None and "media_url" in self.model_fields_set:
            _dict['mediaURL'] = None

        # set to None if additional_info_url (nullable) is None
        # and model_fields_set contains the field
        if self.additional_info_url is None and "additional_info_url" in self.model_fields_set:
            _dict['additionalInfoURL'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['isActive'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Lounge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "displayedPrice": obj.get("displayedPrice"),
            "orderNumber": obj.get("orderNumber"),
            "mediaURL": obj.get("mediaURL"),
            "additionalInfoURL": obj.get("additionalInfoURL"),
            "id": AmenityId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "isActive": obj.get("isActive"),
            "merchantID": obj.get("merchantID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


