# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-14T04:24:40.846Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from wallet.models.ms_member_redemption_register_id import MSMemberRedemptionRegisterID
from wallet.models.ms_member_redemption_transaction_type import MSMemberRedemptionTransactionType
from typing import Optional, Set
from typing_extensions import Self

class MSMemberRedemption(BaseModel):
    """
    MSMemberRedemption
    """ # noqa: E501
    transaction_id: Optional[Any] = Field(description="The transaction ID at the POS", alias="transactionID")
    transaction_type: MSMemberRedemptionTransactionType = Field(alias="transactionType")
    points: Optional[Any] = Field(description="The number of points involved in this transaction")
    register_id: Optional[MSMemberRedemptionRegisterID] = Field(default=None, alias="registerID")
    terminal_type: Optional[Any] = Field(description="The type of the terminal", alias="terminalType")
    id: Optional[Any] = Field(description="The UUID of this record")
    member_id: Annotated[str, Field(min_length=10, strict=True, max_length=10)] = Field(alias="memberID")
    merchant_id: Annotated[str, Field(min_length=10, strict=True, max_length=10)] = Field(alias="merchantID")
    created_at: Optional[Any] = Field(description="The timestamp of when this resource was created", alias="createdAt")
    is_active: Optional[Any] = Field(description="Denotes if this resource is active", alias="isActive")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["transactionID", "transactionType", "points", "registerID", "terminalType", "id", "memberID", "merchantID", "createdAt", "isActive"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MSMemberRedemption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of transaction_type
        if self.transaction_type:
            _dict['transactionType'] = self.transaction_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of register_id
        if self.register_id:
            _dict['registerID'] = self.register_id.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if transaction_id (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_id is None and "transaction_id" in self.model_fields_set:
            _dict['transactionID'] = None

        # set to None if points (nullable) is None
        # and model_fields_set contains the field
        if self.points is None and "points" in self.model_fields_set:
            _dict['points'] = None

        # set to None if terminal_type (nullable) is None
        # and model_fields_set contains the field
        if self.terminal_type is None and "terminal_type" in self.model_fields_set:
            _dict['terminalType'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['isActive'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MSMemberRedemption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transactionID": obj.get("transactionID"),
            "transactionType": MSMemberRedemptionTransactionType.from_dict(obj["transactionType"]) if obj.get("transactionType") is not None else None,
            "points": obj.get("points"),
            "registerID": MSMemberRedemptionRegisterID.from_dict(obj["registerID"]) if obj.get("registerID") is not None else None,
            "terminalType": obj.get("terminalType"),
            "id": obj.get("id"),
            "memberID": obj.get("memberID"),
            "merchantID": obj.get("merchantID"),
            "createdAt": obj.get("createdAt"),
            "isActive": obj.get("isActive")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


