# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-25T21:35:51.140Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from wallet.models.business_type import BusinessType
from typing import Optional, Set
from typing_extensions import Self

class PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition(BaseModel):
    """
    From T, pick a set of properties whose keys are in the union K
    """ # noqa: E501
    first_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="firstName")
    last_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="lastName")
    email: Annotated[str, Field(min_length=6, strict=True)]
    business_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="businessName")
    business_type: BusinessType = Field(alias="businessType")
    address1: Annotated[str, Field(min_length=1, strict=True)]
    address2: Optional[Annotated[str, Field(min_length=0, strict=True)]] = None
    city: Annotated[str, Field(min_length=3, strict=True)]
    state: Annotated[str, Field(min_length=1, strict=True)]
    postal_code: Annotated[str, Field(min_length=4, strict=True)] = Field(alias="postalCode")
    country: Annotated[str, Field(min_length=2, strict=True)]
    phone_number: Annotated[str, Field(min_length=7, strict=True)] = Field(alias="phoneNumber")
    is_twilio_terms_read: StrictBool = Field(alias="isTwilioTermsRead")
    is_privacy_policy_on_website: StrictBool = Field(alias="isPrivacyPolicyOnWebsite")
    is_tos_on_website: StrictBool = Field(alias="isTosOnWebsite")
    is_stop_understood: StrictBool = Field(alias="isStopUnderstood")
    is_manual_read: StrictBool = Field(alias="isManualRead")
    is_ctia_short_code_read: StrictBool = Field(alias="isCtiaShortCodeRead")
    is_standards_understood: StrictBool = Field(alias="isStandardsUnderstood")
    is_short_code_understood: StrictBool = Field(alias="isShortCodeUnderstood")
    is_opt_in_out_understood: StrictBool = Field(alias="isOptInOutUnderstood")
    is_short_code_transfer_understood: StrictBool = Field(alias="isShortCodeTransferUnderstood")
    is_pricing_understood: StrictBool = Field(alias="isPricingUnderstood")
    is_short_code_timeline_understood: StrictBool = Field(alias="isShortCodeTimelineUnderstood")
    __properties: ClassVar[List[str]] = ["firstName", "lastName", "email", "businessName", "businessType", "address1", "address2", "city", "state", "postalCode", "country", "phoneNumber", "isTwilioTermsRead", "isPrivacyPolicyOnWebsite", "isTosOnWebsite", "isStopUnderstood", "isManualRead", "isCtiaShortCodeRead", "isStandardsUnderstood", "isShortCodeUnderstood", "isOptInOutUnderstood", "isShortCodeTransferUnderstood", "isPricingUnderstood", "isShortCodeTimelineUnderstood"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PickA2PBaseIntakeExcludeKeyofA2PBaseIntakeBusinessClassificationOrBusinessIndustryOrTaxIDTypeOrTaxIDOrWebsiteURLOrSocialMediaURLOrRegionsOfOperationOrMessagingVolumeHighOrJobTitleOrJobPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "businessName": obj.get("businessName"),
            "businessType": obj.get("businessType"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "postalCode": obj.get("postalCode"),
            "country": obj.get("country"),
            "phoneNumber": obj.get("phoneNumber"),
            "isTwilioTermsRead": obj.get("isTwilioTermsRead"),
            "isPrivacyPolicyOnWebsite": obj.get("isPrivacyPolicyOnWebsite"),
            "isTosOnWebsite": obj.get("isTosOnWebsite"),
            "isStopUnderstood": obj.get("isStopUnderstood"),
            "isManualRead": obj.get("isManualRead"),
            "isCtiaShortCodeRead": obj.get("isCtiaShortCodeRead"),
            "isStandardsUnderstood": obj.get("isStandardsUnderstood"),
            "isShortCodeUnderstood": obj.get("isShortCodeUnderstood"),
            "isOptInOutUnderstood": obj.get("isOptInOutUnderstood"),
            "isShortCodeTransferUnderstood": obj.get("isShortCodeTransferUnderstood"),
            "isPricingUnderstood": obj.get("isPricingUnderstood"),
            "isShortCodeTimelineUnderstood": obj.get("isShortCodeTimelineUnderstood")
        })
        return _obj


