# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.38.1**, built 2026-08-21T22:01:54.587Z

    The version of the OpenAPI document: 2.38.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionFeature(BaseModel):
    """
    SubscriptionFeature
    """ # noqa: E501
    sort_num: Optional[Any] = Field(alias="sortNum")
    name: Optional[Any]
    slug: Optional[Any] = None
    max_volume: Optional[Any] = Field(default=None, alias="maxVolume")
    measurement: Optional[Any]
    description: Optional[Any]
    current_volume: Optional[Any] = Field(default=None, alias="currentVolume")
    is_exceeded: Optional[Any] = Field(default=None, alias="isExceeded")
    is_in_use: Optional[Any] = Field(default=None, alias="isInUse")
    is_enabled: Optional[Any] = Field(default=None, alias="isEnabled")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["sortNum", "name", "slug", "maxVolume", "measurement", "description", "currentVolume", "isExceeded", "isInUse", "isEnabled"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionFeature from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if sort_num (nullable) is None
        # and model_fields_set contains the field
        if self.sort_num is None and "sort_num" in self.model_fields_set:
            _dict['sortNum'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if max_volume (nullable) is None
        # and model_fields_set contains the field
        if self.max_volume is None and "max_volume" in self.model_fields_set:
            _dict['maxVolume'] = None

        # set to None if measurement (nullable) is None
        # and model_fields_set contains the field
        if self.measurement is None and "measurement" in self.model_fields_set:
            _dict['measurement'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if current_volume (nullable) is None
        # and model_fields_set contains the field
        if self.current_volume is None and "current_volume" in self.model_fields_set:
            _dict['currentVolume'] = None

        # set to None if is_exceeded (nullable) is None
        # and model_fields_set contains the field
        if self.is_exceeded is None and "is_exceeded" in self.model_fields_set:
            _dict['isExceeded'] = None

        # set to None if is_in_use (nullable) is None
        # and model_fields_set contains the field
        if self.is_in_use is None and "is_in_use" in self.model_fields_set:
            _dict['isInUse'] = None

        # set to None if is_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_enabled is None and "is_enabled" in self.model_fields_set:
            _dict['isEnabled'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionFeature from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sortNum": obj.get("sortNum"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "maxVolume": obj.get("maxVolume"),
            "measurement": obj.get("measurement"),
            "description": obj.get("description"),
            "currentVolume": obj.get("currentVolume"),
            "isExceeded": obj.get("isExceeded"),
            "isInUse": obj.get("isInUse"),
            "isEnabled": obj.get("isEnabled")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


