# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.49.0**, built 2026-09-18T02:27:10.027Z

    The version of the OpenAPI document: 2.49.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WTApplePassStyle(BaseModel):
    """
    WTApplePassStyle
    """ # noqa: E501
    background_color: Optional[Any] = Field(default=None, alias="backgroundColor")
    foreground_color: Optional[Any] = Field(default=None, alias="foregroundColor")
    label_color: Optional[Any] = Field(default=None, alias="labelColor")
    strip_color: Optional[Any] = Field(default=None, alias="stripColor")
    logo_url: Optional[Any] = Field(default=None, alias="logoUrl")
    icon_url: Optional[Any] = Field(default=None, alias="iconUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["backgroundColor", "foregroundColor", "labelColor", "stripColor", "logoUrl", "iconUrl"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WTApplePassStyle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if background_color (nullable) is None
        # and model_fields_set contains the field
        if self.background_color is None and "background_color" in self.model_fields_set:
            _dict['backgroundColor'] = None

        # set to None if foreground_color (nullable) is None
        # and model_fields_set contains the field
        if self.foreground_color is None and "foreground_color" in self.model_fields_set:
            _dict['foregroundColor'] = None

        # set to None if label_color (nullable) is None
        # and model_fields_set contains the field
        if self.label_color is None and "label_color" in self.model_fields_set:
            _dict['labelColor'] = None

        # set to None if strip_color (nullable) is None
        # and model_fields_set contains the field
        if self.strip_color is None and "strip_color" in self.model_fields_set:
            _dict['stripColor'] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['logoUrl'] = None

        # set to None if icon_url (nullable) is None
        # and model_fields_set contains the field
        if self.icon_url is None and "icon_url" in self.model_fields_set:
            _dict['iconUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WTApplePassStyle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backgroundColor": obj.get("backgroundColor"),
            "foregroundColor": obj.get("foregroundColor"),
            "labelColor": obj.get("labelColor"),
            "stripColor": obj.get("stripColor"),
            "logoUrl": obj.get("logoUrl"),
            "iconUrl": obj.get("iconUrl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


