# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-22T16:21:50.429Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WTLeadFiCreditOffer(BaseModel):
    """
    WTLeadFiCreditOffer
    """ # noqa: E501
    name: Optional[Any] = None
    details: Optional[Any] = None
    status: Optional[Any] = None
    amount: Optional[Any] = None
    contingencies: Optional[Any] = None
    debt_to_income: Optional[Any] = Field(default=None, alias="debtToIncome")
    monthly_payments: Optional[Any] = Field(default=None, alias="monthlyPayments")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "details", "status", "amount", "contingencies", "debtToIncome", "monthlyPayments"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WTLeadFiCreditOffer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if details (nullable) is None
        # and model_fields_set contains the field
        if self.details is None and "details" in self.model_fields_set:
            _dict['details'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if contingencies (nullable) is None
        # and model_fields_set contains the field
        if self.contingencies is None and "contingencies" in self.model_fields_set:
            _dict['contingencies'] = None

        # set to None if debt_to_income (nullable) is None
        # and model_fields_set contains the field
        if self.debt_to_income is None and "debt_to_income" in self.model_fields_set:
            _dict['debtToIncome'] = None

        # set to None if monthly_payments (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_payments is None and "monthly_payments" in self.model_fields_set:
            _dict['monthlyPayments'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WTLeadFiCreditOffer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "details": obj.get("details"),
            "status": obj.get("status"),
            "amount": obj.get("amount"),
            "contingencies": obj.get("contingencies"),
            "debtToIncome": obj.get("debtToIncome"),
            "monthlyPayments": obj.get("monthlyPayments")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


