# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.4.1**, built 2026-07-11T13:18:56.541Z

    The version of the OpenAPI document: 2.4.1
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List, Optional
from wallet.models.wt_lead_fi_consumer_profile_address import WTLeadFiConsumerProfileAddress
from wallet.models.wt_lead_fi_consumer_profile_assets import WTLeadFiConsumerProfileAssets
from wallet.models.wt_lead_fi_consumer_profile_income import WTLeadFiConsumerProfileIncome
from typing import Optional, Set
from typing_extensions import Self

class WTLeadFiConsumerProfile(BaseModel):
    """
    WTLeadFiConsumerProfile
    """ # noqa: E501
    age: Optional[Any] = None
    phones: Optional[Any]
    address: Optional[WTLeadFiConsumerProfileAddress] = None
    income: Optional[WTLeadFiConsumerProfileIncome] = None
    assets: Optional[WTLeadFiConsumerProfileAssets] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["age", "phones", "address", "income", "assets"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WTLeadFiConsumerProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of income
        if self.income:
            _dict['income'] = self.income.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assets
        if self.assets:
            _dict['assets'] = self.assets.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if age (nullable) is None
        # and model_fields_set contains the field
        if self.age is None and "age" in self.model_fields_set:
            _dict['age'] = None

        # set to None if phones (nullable) is None
        # and model_fields_set contains the field
        if self.phones is None and "phones" in self.model_fields_set:
            _dict['phones'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WTLeadFiConsumerProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age": obj.get("age"),
            "phones": obj.get("phones"),
            "address": WTLeadFiConsumerProfileAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "income": WTLeadFiConsumerProfileIncome.from_dict(obj["income"]) if obj.get("income") is not None else None,
            "assets": WTLeadFiConsumerProfileAssets.from_dict(obj["assets"]) if obj.get("assets") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


