# coding: utf-8

"""
    wallet-api

    Wallet Inc. API reference.  **Spec version 2.50.0**, built 2026-10-01T10:08:33.203Z

    The version of the OpenAPI document: 2.50.0
    Contact: development@wallet.inc
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List
from wallet.models.wt_apple_pass_style import WTApplePassStyle
from typing import Optional, Set
from typing_extensions import Self

class WTPassStyleResponseApple(BaseModel):
    """
    WTPassStyleResponseApple
    """ # noqa: E501
    effective: WTApplePassStyle
    style: WTApplePassStyle
    __properties: ClassVar[List[str]] = ["effective", "style"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WTPassStyleResponseApple from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of effective
        if self.effective:
            _dict['effective'] = self.effective.to_dict()
        # override the default output from pydantic by calling `to_dict()` of style
        if self.style:
            _dict['style'] = self.style.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WTPassStyleResponseApple from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "effective": WTApplePassStyle.from_dict(obj["effective"]) if obj.get("effective") is not None else None,
            "style": WTApplePassStyle.from_dict(obj["style"]) if obj.get("style") is not None else None
        })
        return _obj


